"""Post-process nanobot config for portable setup.

Usage:
    python post_config.py <config_path> <root_dir>

Reads the config generated by `nanobot onboard` and adds:
- Custom provider with env-var API key
- CLI channel
- Portable-friendly exec pathAppend
- Workspace path adjustment
- Lite auto-disabled skills (Windows-incompatible upstream skills)
"""

import json
import os
import re
import shutil
import sys


_ENV_REF_RE = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")

# Skills not usable on Windows host. See AGENTS.md "Skills auto-disabled by Lite".
_LITE_DISABLED_SKILLS = ["summarize", "tmux"]


def collect_env_refs(config: dict) -> list[str]:
    """Walk config, return sorted list of all ${VAR} names found in string values."""
    refs: set[str] = set()

    def walk(obj):
        if isinstance(obj, str):
            for m in _ENV_REF_RE.finditer(obj):
                refs.add(m.group(1))
        elif isinstance(obj, dict):
            for v in obj.values():
                walk(v)
        elif isinstance(obj, list):
            for v in obj:
                walk(v)

    walk(config)
    return sorted(refs)


def sync_env_template(env_path: str, expected_vars: list[str]) -> None:
    """Ensure .env has every VAR referenced by config. Append VAR=null for missing.
    Never overwrite existing values."""
    existing: dict[str, str] = {}
    if os.path.isfile(env_path):
        for raw in open(env_path, encoding="utf-8"):
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            existing[k.strip()] = v.strip()

    appended: list[str] = []
    for var in expected_vars:
        if var not in existing:
            existing[var] = "null"
            appended.append(var)

    if not appended and os.path.isfile(env_path):
        print(f"[OK] .env already in sync ({len(existing)} entries, no append needed)")
        return

    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# Nanobot Portable - Environment Variables\n")
        f.write("# Auto-generated from config.json ${...} references.\n")
        f.write("# Edit active provider's keys via edit_env.bat\n")
        f.write("# Inactive providers stay =null (loader requires env var to be set)\n")
        f.write("# =========================================\n\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")

    if appended:
        print(f"[OK] .env synced: appended {len(appended)} new keys ({', '.join(appended)})")
    else:
        print(f"[OK] .env created: {len(existing)} entries from config references")


def main():
    if len(sys.argv) < 3:
        print("Usage: post_config.py <config_path> <root_dir>")
        sys.exit(1)

    config_path = sys.argv[1]
    root_dir = sys.argv[2]

    if not os.path.isfile(config_path):
        print(f"[ERROR] Config not found: {config_path}")
        sys.exit(1)

    # Backup before modification
    bak_path = config_path + '.bak'
    if not os.path.isfile(bak_path):
        shutil.copy2(config_path, bak_path)
        print(f"[BAK] Backup: {bak_path}")
    else:
        print(f"[BAK] Already available, skip: {bak_path}")

    with open(config_path, 'r', encoding='utf-8') as f:
        config = json.load(f)

    # === providers ===
    if 'providers' not in config:
        config['providers'] = {}
    config['providers']['custom'] = {
        "apiKey": "${NANOBOT_CUSTOM_API_KEY}",
        "apiBase": "${NANOBOT_CUSTOM_API_BASE}",
        "apiType": "auto"
    }

    # === agents.defaults ===
    defaults = config.get('agents', {}).get('defaults', {})
    defaults['model'] = 'sengkuni-1.0'
    defaults['provider'] = 'custom'
    # Don't override workspace if user already set it

    existing = defaults.get('disabledSkills', [])
    defaults['disabledSkills'] = list(dict.fromkeys([*existing, *_LITE_DISABLED_SKILLS]))

    # === channels ===
    if 'channels' not in config:
        config['channels'] = {}
    config['channels']['cli'] = {"enabled": True}
    config['channels'].setdefault('websocket', {})['enabled'] = True

    # === tools.exec ===
    tools = config.get('tools', {})
    tools.setdefault('exec', {})
    # pathAppend left empty: _build_env() on Windows inherits PATH from the parent
    # process (launcher already prepends $PortablePaths). Absolute paths would break
    # on USB drive letter changes; relative paths would break if workspace is moved
    # outside root. Inherited PATH is correct regardless of either.
    # restrictToWorkspace is at tools level (not tools.exec) — ExecToolConfig
    # doesn't have this field; upstream ToolsConfig.restrict_to_workspace does.
    tools['restrictToWorkspace'] = True

    # === write back ===
    with open(config_path, 'w', encoding='utf-8') as f:
        json.dump(config, f, indent=2, ensure_ascii=False)

    # === sync .env template with config references ===
    env_path = os.path.join(os.path.dirname(config_path), ".env")
    expected = collect_env_refs(config)
    if expected:
        sync_env_template(env_path, expected)
    else:
        print("[INFO] No ${VAR} references in config; .env not touched")

    print(f"[OK] Config post-processed: {config_path}")


if __name__ == '__main__':
    main()
